# -*- coding: utf-8 -*-
"""pandas_pt2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JWYH0SN-itiTl44U_NO1Tf6WFKgBtrhx
"""

from io import StringIO
import pandas as pd
df = pd.read_csv('/content/mercedesbenz.csv')
df.head()





"""learnin to reading csv fole stringIo in pandas


"""

pd.read_csv('/content/mercedesbenz.csv')

data=('col1,col2,col3\n'
      'x,y,1\n'
      'a,b,c\n'
       'e,f,e')

type(data)

## in memory file format object
StringIO(data)

pd.read_csv(StringIO(data))

pd.read_csv(StringIO(data),usecols=['col1','col2'])

df = pd.read_csv('/content/mercedesbenz.csv', usecols=['X0','X1','X2','X3'])
df.head()

df.to_csv('test.csv')

df.to_csv('test1.csv',index=False)

## Datatypes in csv
data=('col1,col2,col3\n'
      'x,y,1,3\n'
      'a,b,c,4\n'
       'e,f,e')
df=pd.read_csv(StringIO(data))
df.info()

df=pd.read_csv(StringIO(data),dtype='object')

df=pd.read_csv(StringIO(data),dtype='string')

df.info()

df.isnull().sum()

data = ('a,b,c,d\n'
        '1,2,3,4\n'
        '5,6,7,8\n'
        '9,10,11')
df=pd.read_csv(StringIO(data),dtype={'a':int,'b':float,'c':int})
df.info()

df.dtypes

data = ('index,a,b,c\n'
        '4,apple,bat,5.7\n'
        '8,orange,cow,10')



pd.read_csv(StringIO(data),index_col=0)

data = ('index,a,b,c\n'
        '4,apple,bat,5.7\n'
        '8,orange,cow,10')
pd.read_csv(StringIO(data),usecols=['a','b','c'],index_col=0)



